version: '3'
dotenv: ['../.env']
vars:
  MODULE_NAME: "Database"

includes:
  version: ../Taskfile.version.yml
  production: ../Taskfile.prod.yml

tasks:
  default:
    desc: "Development build of the {{.MODULE_NAME}} module"
    cmds:
      - echo "Building {{.MODULE_NAME}} module..."
      - go get -u
      - go mod tidy
      - go mod verify
      - go vet ./...
      - go build ./...
      - go test -race -run Test ./... -short
      - task: clean
      - echo "✓ {{.MODULE_NAME}} module build complete"

  prod:
    cmds:
      - task: production:prod

  clean:
    desc: "Clean up build artifacts"
    cmds:
      - rm -rf ./relative
      - rm -rf ./data
      - echo "Build artifacts cleaned"

  docker:start:
    desc: "Start Docker containers for {{.MODULE_NAME}}"
    dir: ./postgres
    cmds:
      - docker-compose up -d
      - echo "✓ Docker containers started"

  docker:stop:
    desc: "Stop Docker containers for {{.MODULE_NAME}}"
    dir: ./postgres
    cmds:
      - docker-compose stop
      - echo "✓ Docker containers stopped"

  docker:cleanup:
    desc: "Stop and remove Docker containers, networks, and volumes"
    dir: ./postgres
    cmds:
      - docker-compose down -v
      - echo "✓ Docker cleanup complete"

  sqlite:db:
    desc: "Generate SQL boilerplate code for SQLite database"
    cmds:
      - rm -rf ../build/db/data.db
      - go run ./sqlite/example/main.go
  sqlite:sqlboiler:
    deps: [sqlite:db]
    desc: "Generate SQL boilerplate code using SQLBoiler for SQLite"
    dir: ./sqlite
      - sqlboiler sqlite3
      - echo "✓ SQLite SQL boilerplate generated"