// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	APIKeys string
	Logbook string
	Qso     string
}{
	APIKeys: "api_keys",
	Logbook: "logbook",
	Qso:     "qso",
}
