// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Logbook is an object representing the database table.
type Logbook struct {
	ID          int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt   time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ModifiedAt  null.Time   `boil:"modified_at" json:"modified_at,omitempty" toml:"modified_at" yaml:"modified_at,omitempty"`
	UserID      int64       `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Name        string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Callsign    string      `boil:"callsign" json:"callsign" toml:"callsign" yaml:"callsign"`
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`

	R *logbookR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L logbookL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var LogbookColumns = struct {
	ID          string
	CreatedAt   string
	ModifiedAt  string
	UserID      string
	Name        string
	Callsign    string
	Description string
}{
	ID:          "id",
	CreatedAt:   "created_at",
	ModifiedAt:  "modified_at",
	UserID:      "user_id",
	Name:        "name",
	Callsign:    "callsign",
	Description: "description",
}

var LogbookTableColumns = struct {
	ID          string
	CreatedAt   string
	ModifiedAt  string
	UserID      string
	Name        string
	Callsign    string
	Description string
}{
	ID:          "logbook.id",
	CreatedAt:   "logbook.created_at",
	ModifiedAt:  "logbook.modified_at",
	UserID:      "logbook.user_id",
	Name:        "logbook.name",
	Callsign:    "logbook.callsign",
	Description: "logbook.description",
}

// Generated where

var LogbookWhere = struct {
	ID          whereHelperint64
	CreatedAt   whereHelpertime_Time
	ModifiedAt  whereHelpernull_Time
	UserID      whereHelperint64
	Name        whereHelperstring
	Callsign    whereHelperstring
	Description whereHelpernull_String
}{
	ID:          whereHelperint64{field: "\"logbook\".\"id\""},
	CreatedAt:   whereHelpertime_Time{field: "\"logbook\".\"created_at\""},
	ModifiedAt:  whereHelpernull_Time{field: "\"logbook\".\"modified_at\""},
	UserID:      whereHelperint64{field: "\"logbook\".\"user_id\""},
	Name:        whereHelperstring{field: "\"logbook\".\"name\""},
	Callsign:    whereHelperstring{field: "\"logbook\".\"callsign\""},
	Description: whereHelpernull_String{field: "\"logbook\".\"description\""},
}

// LogbookRels is where relationship names are stored.
var LogbookRels = struct {
	User   string
	APIKey string
	Qsos   string
}{
	User:   "User",
	APIKey: "APIKey",
	Qsos:   "Qsos",
}

// logbookR is where relationships are stored.
type logbookR struct {
	User   *User    `boil:"User" json:"User" toml:"User" yaml:"User"`
	APIKey *APIKey  `boil:"APIKey" json:"APIKey" toml:"APIKey" yaml:"APIKey"`
	Qsos   QsoSlice `boil:"Qsos" json:"Qsos" toml:"Qsos" yaml:"Qsos"`
}

// NewStruct creates a new relationship struct
func (*logbookR) NewStruct() *logbookR {
	return &logbookR{}
}

func (o *Logbook) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *logbookR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

func (o *Logbook) GetAPIKey() *APIKey {
	if o == nil {
		return nil
	}

	return o.R.GetAPIKey()
}

func (r *logbookR) GetAPIKey() *APIKey {
	if r == nil {
		return nil
	}

	return r.APIKey
}

func (o *Logbook) GetQsos() QsoSlice {
	if o == nil {
		return nil
	}

	return o.R.GetQsos()
}

func (r *logbookR) GetQsos() QsoSlice {
	if r == nil {
		return nil
	}

	return r.Qsos
}

// logbookL is where Load methods for each relationship are stored.
type logbookL struct{}

var (
	logbookAllColumns            = []string{"id", "created_at", "modified_at", "user_id", "name", "callsign", "description"}
	logbookColumnsWithoutDefault = []string{"user_id", "name", "callsign"}
	logbookColumnsWithDefault    = []string{"id", "created_at", "modified_at", "description"}
	logbookPrimaryKeyColumns     = []string{"id"}
	logbookGeneratedColumns      = []string{}
)

type (
	// LogbookSlice is an alias for a slice of pointers to Logbook.
	// This should almost always be used instead of []Logbook.
	LogbookSlice []*Logbook

	logbookQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	logbookType                 = reflect.TypeOf(&Logbook{})
	logbookMapping              = queries.MakeStructMapping(logbookType)
	logbookPrimaryKeyMapping, _ = queries.BindMapping(logbookType, logbookMapping, logbookPrimaryKeyColumns)
	logbookInsertCacheMut       sync.RWMutex
	logbookInsertCache          = make(map[string]insertCache)
	logbookUpdateCacheMut       sync.RWMutex
	logbookUpdateCache          = make(map[string]updateCache)
	logbookUpsertCacheMut       sync.RWMutex
	logbookUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single logbook record from the query.
func (q logbookQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Logbook, error) {
	o := &Logbook{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for logbook")
	}

	return o, nil
}

// All returns all Logbook records from the query.
func (q logbookQuery) All(ctx context.Context, exec boil.ContextExecutor) (LogbookSlice, error) {
	var o []*Logbook

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Logbook slice")
	}

	return o, nil
}

// Count returns the count of all Logbook records in the query.
func (q logbookQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count logbook rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q logbookQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if logbook exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *Logbook) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// APIKey pointed to by the foreign key.
func (o *Logbook) APIKey(mods ...qm.QueryMod) apiKeyQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"logbook_id\" = ?", o.ID),
	}

	queryMods = append(queryMods, mods...)

	return APIKeys(queryMods...)
}

// Qsos retrieves all the qso's Qsos with an executor.
func (o *Logbook) Qsos(mods ...qm.QueryMod) qsoQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"qso\".\"logbook_id\"=?", o.ID),
	)

	return Qsos(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (logbookL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeLogbook interface{}, mods queries.Applicator) error {
	var slice []*Logbook
	var object *Logbook

	if singular {
		var ok bool
		object, ok = maybeLogbook.(*Logbook)
		if !ok {
			object = new(Logbook)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeLogbook)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeLogbook))
			}
		}
	} else {
		s, ok := maybeLogbook.(*[]*Logbook)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeLogbook)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeLogbook))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &logbookR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &logbookR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Logbooks = append(foreign.R.Logbooks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Logbooks = append(foreign.R.Logbooks, local)
				break
			}
		}
	}

	return nil
}

// LoadAPIKey allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-1 relationship.
func (logbookL) LoadAPIKey(ctx context.Context, e boil.ContextExecutor, singular bool, maybeLogbook interface{}, mods queries.Applicator) error {
	var slice []*Logbook
	var object *Logbook

	if singular {
		var ok bool
		object, ok = maybeLogbook.(*Logbook)
		if !ok {
			object = new(Logbook)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeLogbook)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeLogbook))
			}
		}
	} else {
		s, ok := maybeLogbook.(*[]*Logbook)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeLogbook)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeLogbook))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &logbookR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &logbookR{}
			}

			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`api_keys`),
		qm.WhereIn(`api_keys.logbook_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load APIKey")
	}

	var resultSlice []*APIKey
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice APIKey")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for api_keys")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for api_keys")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.APIKey = foreign
		if foreign.R == nil {
			foreign.R = &apiKeyR{}
		}
		foreign.R.Logbook = object
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ID == foreign.LogbookID {
				local.R.APIKey = foreign
				if foreign.R == nil {
					foreign.R = &apiKeyR{}
				}
				foreign.R.Logbook = local
				break
			}
		}
	}

	return nil
}

// LoadQsos allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (logbookL) LoadQsos(ctx context.Context, e boil.ContextExecutor, singular bool, maybeLogbook interface{}, mods queries.Applicator) error {
	var slice []*Logbook
	var object *Logbook

	if singular {
		var ok bool
		object, ok = maybeLogbook.(*Logbook)
		if !ok {
			object = new(Logbook)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeLogbook)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeLogbook))
			}
		}
	} else {
		s, ok := maybeLogbook.(*[]*Logbook)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeLogbook)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeLogbook))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &logbookR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &logbookR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`qso`),
		qm.WhereIn(`qso.logbook_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load qso")
	}

	var resultSlice []*Qso
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice qso")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on qso")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for qso")
	}

	if singular {
		object.R.Qsos = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &qsoR{}
			}
			foreign.R.Logbook = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.LogbookID {
				local.R.Qsos = append(local.R.Qsos, foreign)
				if foreign.R == nil {
					foreign.R = &qsoR{}
				}
				foreign.R.Logbook = local
				break
			}
		}
	}

	return nil
}

// SetUser of the logbook to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Logbooks.
func (o *Logbook) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"logbook\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, logbookPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &logbookR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Logbooks: LogbookSlice{o},
		}
	} else {
		related.R.Logbooks = append(related.R.Logbooks, o)
	}

	return nil
}

// SetAPIKey of the logbook to the related item.
// Sets o.R.APIKey to related.
// Adds o to related.R.Logbook.
func (o *Logbook) SetAPIKey(ctx context.Context, exec boil.ContextExecutor, insert bool, related *APIKey) error {
	var err error

	if insert {
		related.LogbookID = o.ID

		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	} else {
		updateQuery := fmt.Sprintf(
			"UPDATE \"api_keys\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, []string{"logbook_id"}),
			strmangle.WhereClause("\"", "\"", 2, apiKeyPrimaryKeyColumns),
		)
		values := []interface{}{o.ID, related.ID}

		if boil.IsDebug(ctx) {
			writer := boil.DebugWriterFrom(ctx)
			fmt.Fprintln(writer, updateQuery)
			fmt.Fprintln(writer, values)
		}
		if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
			return errors.Wrap(err, "failed to update foreign table")
		}

		related.LogbookID = o.ID
	}

	if o.R == nil {
		o.R = &logbookR{
			APIKey: related,
		}
	} else {
		o.R.APIKey = related
	}

	if related.R == nil {
		related.R = &apiKeyR{
			Logbook: o,
		}
	} else {
		related.R.Logbook = o
	}
	return nil
}

// AddQsos adds the given related objects to the existing relationships
// of the logbook, optionally inserting them as new records.
// Appends related to o.R.Qsos.
// Sets related.R.Logbook appropriately.
func (o *Logbook) AddQsos(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Qso) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.LogbookID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"qso\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"logbook_id"}),
				strmangle.WhereClause("\"", "\"", 2, qsoPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.LogbookID = o.ID
		}
	}

	if o.R == nil {
		o.R = &logbookR{
			Qsos: related,
		}
	} else {
		o.R.Qsos = append(o.R.Qsos, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &qsoR{
				Logbook: o,
			}
		} else {
			rel.R.Logbook = o
		}
	}
	return nil
}

// Logbooks retrieves all the records using an executor.
func Logbooks(mods ...qm.QueryMod) logbookQuery {
	mods = append(mods, qm.From("\"logbook\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"logbook\".*"})
	}

	return logbookQuery{q}
}

// FindLogbook retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLogbook(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Logbook, error) {
	logbookObj := &Logbook{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"logbook\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, logbookObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from logbook")
	}

	return logbookObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Logbook) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no logbook provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(logbookColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	logbookInsertCacheMut.RLock()
	cache, cached := logbookInsertCache[key]
	logbookInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			logbookAllColumns,
			logbookColumnsWithDefault,
			logbookColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(logbookType, logbookMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(logbookType, logbookMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"logbook\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"logbook\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into logbook")
	}

	if !cached {
		logbookInsertCacheMut.Lock()
		logbookInsertCache[key] = cache
		logbookInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Logbook.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Logbook) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	logbookUpdateCacheMut.RLock()
	cache, cached := logbookUpdateCache[key]
	logbookUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			logbookAllColumns,
			logbookPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update logbook, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"logbook\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, logbookPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(logbookType, logbookMapping, append(wl, logbookPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update logbook row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for logbook")
	}

	if !cached {
		logbookUpdateCacheMut.Lock()
		logbookUpdateCache[key] = cache
		logbookUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q logbookQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for logbook")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for logbook")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LogbookSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), logbookPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"logbook\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, logbookPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in logbook slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all logbook")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Logbook) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no logbook provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(logbookColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	logbookUpsertCacheMut.RLock()
	cache, cached := logbookUpsertCache[key]
	logbookUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			logbookAllColumns,
			logbookColumnsWithDefault,
			logbookColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			logbookAllColumns,
			logbookPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert logbook, could not build update column list")
		}

		ret := strmangle.SetComplement(logbookAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(logbookPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert logbook, could not build conflict column list")
			}

			conflict = make([]string, len(logbookPrimaryKeyColumns))
			copy(conflict, logbookPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"logbook\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(logbookType, logbookMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(logbookType, logbookMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert logbook")
	}

	if !cached {
		logbookUpsertCacheMut.Lock()
		logbookUpsertCache[key] = cache
		logbookUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Logbook record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Logbook) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Logbook provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), logbookPrimaryKeyMapping)
	sql := "DELETE FROM \"logbook\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from logbook")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for logbook")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q logbookQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no logbookQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from logbook")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for logbook")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LogbookSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), logbookPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"logbook\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, logbookPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from logbook slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for logbook")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Logbook) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindLogbook(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LogbookSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := LogbookSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), logbookPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"logbook\".* FROM \"logbook\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, logbookPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in LogbookSlice")
	}

	*o = slice

	return nil
}

// LogbookExists checks if the Logbook row exists.
func LogbookExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"logbook\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if logbook exists")
	}

	return exists, nil
}

// Exists checks if the Logbook row exists.
func (o *Logbook) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return LogbookExists(ctx, exec, o.ID)
}
