// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// QsoUpload is an object representing the database table.
type QsoUpload struct {
	ID            null.Int64  `boil:"id" json:"id,omitempty" toml:"id" yaml:"id,omitempty"`
	QsoID         int64       `boil:"qso_id" json:"qso_id" toml:"qso_id" yaml:"qso_id"`
	Service       string      `boil:"service" json:"service" toml:"service" yaml:"service"`
	Status        string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	UploadedAt    null.Time   `boil:"uploaded_at" json:"uploaded_at,omitempty" toml:"uploaded_at" yaml:"uploaded_at,omitempty"`
	NextAttemptAt null.Time   `boil:"next_attempt_at" json:"next_attempt_at,omitempty" toml:"next_attempt_at" yaml:"next_attempt_at,omitempty"`
	Attempts      int64       `boil:"attempts" json:"attempts" toml:"attempts" yaml:"attempts"`
	LastError     null.String `boil:"last_error" json:"last_error,omitempty" toml:"last_error" yaml:"last_error,omitempty"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *qsoUploadR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L qsoUploadL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var QsoUploadColumns = struct {
	ID            string
	QsoID         string
	Service       string
	Status        string
	UploadedAt    string
	NextAttemptAt string
	Attempts      string
	LastError     string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	QsoID:         "qso_id",
	Service:       "service",
	Status:        "status",
	UploadedAt:    "uploaded_at",
	NextAttemptAt: "next_attempt_at",
	Attempts:      "attempts",
	LastError:     "last_error",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var QsoUploadTableColumns = struct {
	ID            string
	QsoID         string
	Service       string
	Status        string
	UploadedAt    string
	NextAttemptAt string
	Attempts      string
	LastError     string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "qso_upload.id",
	QsoID:         "qso_upload.qso_id",
	Service:       "qso_upload.service",
	Status:        "qso_upload.status",
	UploadedAt:    "qso_upload.uploaded_at",
	NextAttemptAt: "qso_upload.next_attempt_at",
	Attempts:      "qso_upload.attempts",
	LastError:     "qso_upload.last_error",
	CreatedAt:     "qso_upload.created_at",
	UpdatedAt:     "qso_upload.updated_at",
}

// Generated where

type whereHelpernull_Int64 struct{ field string }

func (w whereHelpernull_Int64) EQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int64) NEQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int64) LT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int64) LTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int64) GT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int64) GTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var QsoUploadWhere = struct {
	ID            whereHelpernull_Int64
	QsoID         whereHelperint64
	Service       whereHelperstring
	Status        whereHelperstring
	UploadedAt    whereHelpernull_Time
	NextAttemptAt whereHelpernull_Time
	Attempts      whereHelperint64
	LastError     whereHelpernull_String
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	ID:            whereHelpernull_Int64{field: "\"qso_upload\".\"id\""},
	QsoID:         whereHelperint64{field: "\"qso_upload\".\"qso_id\""},
	Service:       whereHelperstring{field: "\"qso_upload\".\"service\""},
	Status:        whereHelperstring{field: "\"qso_upload\".\"status\""},
	UploadedAt:    whereHelpernull_Time{field: "\"qso_upload\".\"uploaded_at\""},
	NextAttemptAt: whereHelpernull_Time{field: "\"qso_upload\".\"next_attempt_at\""},
	Attempts:      whereHelperint64{field: "\"qso_upload\".\"attempts\""},
	LastError:     whereHelpernull_String{field: "\"qso_upload\".\"last_error\""},
	CreatedAt:     whereHelpertime_Time{field: "\"qso_upload\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"qso_upload\".\"updated_at\""},
}

// QsoUploadRels is where relationship names are stored.
var QsoUploadRels = struct {
	Qso string
}{
	Qso: "Qso",
}

// qsoUploadR is where relationships are stored.
type qsoUploadR struct {
	Qso *Qso `boil:"Qso" json:"Qso" toml:"Qso" yaml:"Qso"`
}

// NewStruct creates a new relationship struct
func (*qsoUploadR) NewStruct() *qsoUploadR {
	return &qsoUploadR{}
}

func (o *QsoUpload) GetQso() *Qso {
	if o == nil {
		return nil
	}

	return o.R.GetQso()
}

func (r *qsoUploadR) GetQso() *Qso {
	if r == nil {
		return nil
	}

	return r.Qso
}

// qsoUploadL is where Load methods for each relationship are stored.
type qsoUploadL struct{}

var (
	qsoUploadAllColumns            = []string{"id", "qso_id", "service", "status", "uploaded_at", "next_attempt_at", "attempts", "last_error", "created_at", "updated_at"}
	qsoUploadColumnsWithoutDefault = []string{"qso_id", "service"}
	qsoUploadColumnsWithDefault    = []string{"id", "status", "uploaded_at", "next_attempt_at", "attempts", "last_error", "created_at", "updated_at"}
	qsoUploadPrimaryKeyColumns     = []string{"id"}
	qsoUploadGeneratedColumns      = []string{"id"}
)

type (
	// QsoUploadSlice is an alias for a slice of pointers to QsoUpload.
	// This should almost always be used instead of []QsoUpload.
	QsoUploadSlice []*QsoUpload

	qsoUploadQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	qsoUploadType                 = reflect.TypeOf(&QsoUpload{})
	qsoUploadMapping              = queries.MakeStructMapping(qsoUploadType)
	qsoUploadPrimaryKeyMapping, _ = queries.BindMapping(qsoUploadType, qsoUploadMapping, qsoUploadPrimaryKeyColumns)
	qsoUploadInsertCacheMut       sync.RWMutex
	qsoUploadInsertCache          = make(map[string]insertCache)
	qsoUploadUpdateCacheMut       sync.RWMutex
	qsoUploadUpdateCache          = make(map[string]updateCache)
	qsoUploadUpsertCacheMut       sync.RWMutex
	qsoUploadUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single qsoUpload record from the query.
func (q qsoUploadQuery) One(ctx context.Context, exec boil.ContextExecutor) (*QsoUpload, error) {
	o := &QsoUpload{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for qso_upload")
	}

	return o, nil
}

// All returns all QsoUpload records from the query.
func (q qsoUploadQuery) All(ctx context.Context, exec boil.ContextExecutor) (QsoUploadSlice, error) {
	var o []*QsoUpload

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to QsoUpload slice")
	}

	return o, nil
}

// Count returns the count of all QsoUpload records in the query.
func (q qsoUploadQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count qso_upload rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q qsoUploadQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if qso_upload exists")
	}

	return count > 0, nil
}

// Qso pointed to by the foreign key.
func (o *QsoUpload) Qso(mods ...qm.QueryMod) qsoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.QsoID),
	}

	queryMods = append(queryMods, mods...)

	return Qsos(queryMods...)
}

// LoadQso allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (qsoUploadL) LoadQso(ctx context.Context, e boil.ContextExecutor, singular bool, maybeQsoUpload interface{}, mods queries.Applicator) error {
	var slice []*QsoUpload
	var object *QsoUpload

	if singular {
		var ok bool
		object, ok = maybeQsoUpload.(*QsoUpload)
		if !ok {
			object = new(QsoUpload)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeQsoUpload)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeQsoUpload))
			}
		}
	} else {
		s, ok := maybeQsoUpload.(*[]*QsoUpload)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeQsoUpload)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeQsoUpload))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &qsoUploadR{}
		}
		args[object.QsoID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &qsoUploadR{}
			}

			args[obj.QsoID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`qso`),
		qm.WhereIn(`qso.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`qso.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Qso")
	}

	var resultSlice []*Qso
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Qso")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for qso")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for qso")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Qso = foreign
		if foreign.R == nil {
			foreign.R = &qsoR{}
		}
		foreign.R.QsoUploads = append(foreign.R.QsoUploads, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.QsoID == foreign.ID {
				local.R.Qso = foreign
				if foreign.R == nil {
					foreign.R = &qsoR{}
				}
				foreign.R.QsoUploads = append(foreign.R.QsoUploads, local)
				break
			}
		}
	}

	return nil
}

// SetQso of the qsoUpload to the related item.
// Sets o.R.Qso to related.
// Adds o to related.R.QsoUploads.
func (o *QsoUpload) SetQso(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Qso) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"qso_upload\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"qso_id"}),
		strmangle.WhereClause("\"", "\"", 0, qsoUploadPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.QsoID = related.ID
	if o.R == nil {
		o.R = &qsoUploadR{
			Qso: related,
		}
	} else {
		o.R.Qso = related
	}

	if related.R == nil {
		related.R = &qsoR{
			QsoUploads: QsoUploadSlice{o},
		}
	} else {
		related.R.QsoUploads = append(related.R.QsoUploads, o)
	}

	return nil
}

// QsoUploads retrieves all the records using an executor.
func QsoUploads(mods ...qm.QueryMod) qsoUploadQuery {
	mods = append(mods, qm.From("\"qso_upload\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"qso_upload\".*"})
	}

	return qsoUploadQuery{q}
}

// FindQsoUpload retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindQsoUpload(ctx context.Context, exec boil.ContextExecutor, iD null.Int64, selectCols ...string) (*QsoUpload, error) {
	qsoUploadObj := &QsoUpload{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"qso_upload\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, qsoUploadObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from qso_upload")
	}

	return qsoUploadObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *QsoUpload) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no qso_upload provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(qsoUploadColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	qsoUploadInsertCacheMut.RLock()
	cache, cached := qsoUploadInsertCache[key]
	qsoUploadInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			qsoUploadAllColumns,
			qsoUploadColumnsWithDefault,
			qsoUploadColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, qsoUploadGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(qsoUploadType, qsoUploadMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(qsoUploadType, qsoUploadMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"qso_upload\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"qso_upload\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into qso_upload")
	}

	if !cached {
		qsoUploadInsertCacheMut.Lock()
		qsoUploadInsertCache[key] = cache
		qsoUploadInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the QsoUpload.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *QsoUpload) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	qsoUploadUpdateCacheMut.RLock()
	cache, cached := qsoUploadUpdateCache[key]
	qsoUploadUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			qsoUploadAllColumns,
			qsoUploadPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, qsoUploadGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update qso_upload, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"qso_upload\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, qsoUploadPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(qsoUploadType, qsoUploadMapping, append(wl, qsoUploadPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update qso_upload row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for qso_upload")
	}

	if !cached {
		qsoUploadUpdateCacheMut.Lock()
		qsoUploadUpdateCache[key] = cache
		qsoUploadUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q qsoUploadQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for qso_upload")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for qso_upload")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o QsoUploadSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), qsoUploadPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"qso_upload\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, qsoUploadPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in qsoUpload slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all qsoUpload")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *QsoUpload) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no qso_upload provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(qsoUploadColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	qsoUploadUpsertCacheMut.RLock()
	cache, cached := qsoUploadUpsertCache[key]
	qsoUploadUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			qsoUploadAllColumns,
			qsoUploadColumnsWithDefault,
			qsoUploadColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			qsoUploadAllColumns,
			qsoUploadPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert qso_upload, could not build update column list")
		}

		ret := strmangle.SetComplement(qsoUploadAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(qsoUploadPrimaryKeyColumns))
			copy(conflict, qsoUploadPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"qso_upload\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(qsoUploadType, qsoUploadMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(qsoUploadType, qsoUploadMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert qso_upload")
	}

	if !cached {
		qsoUploadUpsertCacheMut.Lock()
		qsoUploadUpsertCache[key] = cache
		qsoUploadUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single QsoUpload record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *QsoUpload) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no QsoUpload provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), qsoUploadPrimaryKeyMapping)
	sql := "DELETE FROM \"qso_upload\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from qso_upload")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for qso_upload")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q qsoUploadQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no qsoUploadQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from qso_upload")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for qso_upload")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o QsoUploadSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), qsoUploadPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"qso_upload\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, qsoUploadPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from qsoUpload slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for qso_upload")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *QsoUpload) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindQsoUpload(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *QsoUploadSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := QsoUploadSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), qsoUploadPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"qso_upload\".* FROM \"qso_upload\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, qsoUploadPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in QsoUploadSlice")
	}

	*o = slice

	return nil
}

// QsoUploadExists checks if the QsoUpload row exists.
func QsoUploadExists(ctx context.Context, exec boil.ContextExecutor, iD null.Int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"qso_upload\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if qso_upload exists")
	}

	return exists, nil
}

// Exists checks if the QsoUpload row exists.
func (o *QsoUpload) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return QsoUploadExists(ctx, exec, o.ID)
}
